model: lstm

# 数据集
data_path: /home/admin/dataset/RAVDESS-1s  # 数据集路径
class_labels: ["neutral", "calm", "happy", "sad", "angry", "fearful", "disgust", "surprised"]  # 情感标签
# class_labels: ["positive", "negative", "neutral"]
# class_labels: ["angry", "boredom", "disgust", "fear", "happy", "neutral", "sad"]

# 特征存储
feature_path: features/8-category/  # 特征存储路径
train_feature_path_opensmile: features/8-category/train_opensmile_casia.csv  # 训练特征存储路径（Opensmile）
predict_feature_path_opensmile: features/8-category/test_opensmile_casia.csv  # 预测特征存储路径（Opensmile）
train_feature_path_librosa: features/8-category/train_librosa_casia.p  # 训练特征存储路径（librosa）
predict_feature_path_librosa: features/8-category/test_librosa_casia.p  # 预测特征存储路径（librosa）

# 特征提取方式
feature_method: o  # 'o': opensmile, 'l': librosa

# Opensmile 配置，只在 'feature_method: o' 时 需要设置
opensmile_config: IS10_paraling  # Opensmile 标准特征集
opensmile_path: ~/code/tfg/audio_emotion_2.0/opensmile-3.0-linux-x64  # Opensmile 安装路径

# checkpoints
checkpoint_path: checkpoints/  # checkpoint 存储路径
checkpoint_name: LSTM_OPENSMILE_IS10  # checkpoint 文件名

# 训练参数
epochs: 100  # 训练 epoch 数
batch_size: 32  # 批大小
lr: 0.001  # 学习率

# 模型参数
rnn_size: 128  # LSTM 隐藏层大小
hidden_size: 32
dropout: 0.5